# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodbileta', models.IntegerField(verbose_name='КодБилета')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodklienta', models.IntegerField(verbose_name='КодКлиента')),
                ('familiya', models.CharField(max_length=20, verbose_name='Фамилия клиента')),
                ('imya', models.CharField(max_length=20, verbose_name='Имя клиента')),
                ('otchestvo', models.CharField(max_length=20, verbose_name='Отчество клиента')),
                ('vozrast', models.CharField(max_length=20, verbose_name='Возраст')),
                ('skidki', models.CharField(max_length=20, verbose_name='Скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Zaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerzala', models.IntegerField(max_length=10, verbose_name='Номер зала')),
                ('nomermesta', models.IntegerField(max_length=10, verbose_name='Ноаер места')),
                ('nomerryada', models.IntegerField(max_length=10, verbose_name='Номер ряда')),
            ],
        ),
        migrations.AddField(
            model_name='bilet',
            name='kodklienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilets', to='odk.Client'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='nomerzala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilets', to='odk.Zaly'),
        ),
    ]
