# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RenameField(
            model_name='bilet',
            old_name='kodklienta',
            new_name='сlient',
        ),
        migrations.RemoveField(
            model_name='client',
            name='kodklienta',
        ),
    ]
