# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0002_auto_20160229_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='otchestvo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='skidki',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Скидки'),
        ),
    ]
