# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0003_auto_20160402_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vozrast',
            field=models.IntegerField(max_length=20, verbose_name='Возраст'),
        ),
    ]
